name: Suggest a new polyfill
description: Suggest a new polyfill
body:
- type: input
  id: documentation
  attributes:
    label: Provide a link to the method or type you want to polyfill
    placeholder: "https://learn.microsoft.com/en-us/dotnet/api/system.memoryextensions.asspan"
  validations:
    required: true

- type: textarea
  id: other-info
  attributes:
    label: Other information
    placeholder: Other information
  validations:
    required: false
