<Project Sdk="Meziantou.NET.Sdk.Test">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis" Version="5.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Meziantou.Polyfill\Meziantou.Polyfill.csproj" />
  </ItemGroup>

</Project>
