using System.Diagnostics;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Meziantou.Polyfill;

[Generator]
public sealed partial class PolyfillGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
#pragma warning disable RS1035 // Do not use APIs banned for analyzers
        if (Environment.GetEnvironmentVariable("Meziantou_Polyfill_Debug") is "true" or "1")
        {
            if (Debugger.Launch())
            {
                Debugger.Break();
            }
        }
#pragma warning restore RS1035 // Do not use APIs banned for analyzers

        var options = context.AnalyzerConfigOptionsProvider.Select((options, cancellationToken) =>
        {
            return new PolyfillOptions(
                included: GetValueOrDefault(options.GlobalOptions, "build_property.MeziantouPolyfill_IncludedPolyfills"),
                excluded: GetValueOrDefault(options.GlobalOptions, "build_property.MeziantouPolyfill_ExcludedPolyfills"));
        }).WithTrackingName("Options");

        var provider = context.CompilationProvider
            .Combine(options)
            .Select((provider, cancellationToken) => new Members(provider.Left, provider.Right))
            .WithTrackingName("Members");


        context.RegisterImplementationSourceOutput(provider, (context, members) =>
        {
            context.AddSource("Debug.g.cs", SourceText.From(members.DumpAsCSharpComment(), Encoding.UTF8));

            // The EmbeddedAttribute definition is only needed when at least one polyfill is
            // generated; every polyfill source either decorates its types with the attribute
            // (via the rewriter) or contributes to a PolyfillExtensions* host that does.
            if (members.HasAnyPolyfill)
            {
                context.AddSource("Microsoft.CodeAnalysis.EmbeddedAttribute", SourceText.From(""""
                    // <auto-generated/>
                    #pragma warning disable
                    namespace Microsoft.CodeAnalysis
                    {
                        internal sealed partial class EmbeddedAttribute : global::System.Attribute
                        {
                        }
                    }
                    """", encoding: Encoding.UTF8));
            }

            var polyfillExtensions = members.GetPolyfillExtensionsDeclarations();
            if (polyfillExtensions.Length > 0)
            {
                context.AddSource("PolyfillExtensions.g.cs", SourceText.From(polyfillExtensions, Encoding.UTF8));
            }

            members.AddSources(context);
        });
    }

    private static string? GetValueOrDefault(AnalyzerConfigOptions options, string key)
    {
        if (options.TryGetValue(key, out var value))
            return value;

        return null;
    }
}
